name: Run Summarizer Scripts

on:
  schedule:
    # Runs the weekly summarizer at 02:00 UTC every Monday
    - cron: '0 2 * * 1'
    # Runs the monthly summarizer at 03:00 UTC on the 1st day of every month
    - cron: '0 3 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Weekly Summarizer (on Mondays)
      if: github.event.schedule == '0 2 * * 1'
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: python scripts/weekly_summarizer.py

    - name: Run Monthly Summarizer (on 1st of Month)
      if: github.event.schedule == '0 3 1 * *'
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: python scripts/monthly_summarizer.py

    - name: Run Build Index (Manual Trigger)
      if: github.event_name == 'workflow_dispatch'
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: python scripts/build_index.py






